# Site settings
email: dylanwragge@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 


# SEO settings
title: Dylan Wragge
description: Personal website for Dylan Wragge
url: "dylanwragge.com"
twitter_username: 
default_img: 

# Profile settings
name: 
profile_img: 
profile: 
social:
  github: 

# Build settings
exclude: ["Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/
highlighter: rouge
# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer, rouge]

